Fix warnings found by clang: unused private members
For qdeclarativebinding_p.h, since the class is private, there is no
BC guarantee, so we can just remove the members. This class has a
friend, but the friend is also in the same .cpp.

qdeclarativebinding_p.h:139:14: error: private field 'm_object' is not used [-Werror,-Wunused-private-field]
qdeclarativebinding_p.h:140:9: error: private field 'm_index' is not used [-Werror,-Wunused-private-field]

For QSGGeometry, since this is a public class, we can't remove the
members. Just make them unused.

qsggeometry.h:124:11: error: private field 'm_reserved_pointer' is not used [-Werror,-Wunused-private-field]
qsggeometry.h:127:10: error: private field 'm_reserved_bits' is not used [-Werror,-Wunused-private-field]

Change-Id: Ia3650f38f32bd4cd705078a69c5445c64883bce4
Reviewed-by: Alan Alpert <aalpert@blackberry.com>