Fix mistake in using == instead of =
Found by clang:

qml/qdeclarativexmlhttprequest.cpp:1324:24: error: equality comparison result unused [-Werror,-Wunused-comparison]

Change-Id: Ie46678d6102f2e50bf87a53a9cbc14d114b4e334
Reviewed-by: Alan Alpert <aalpert@rim.com>